### ISSUE TITLE
More exchanges

### ISSUE THREAD

**Issue by goldaster** [mikekonan/freqtrade-proxy#20]
Hi! First, congratulate you about this project! It is very useful, thanks!

Are you considering adding more exchanges? If so, I could try to help (right now I don't have time but christmas is coming!). If so, I do program in Python usually but I don't know Go, but I am sure that with very few indications of where is the right code I could help to implement other exchanges, or at least with testing.

Also, I am running it on Windows 10 through Docker. Is there a way to run the code natively (without Docker)?

Thanks!

**Comment by mikekonan** [comment]
Are you considering adding more exchanges? - Yes, it will be really good to integrate binance, but it's not working in my country. Also, I consider starting working on another popular exchange in the future. Also, some minor refactoring is required here. 

Also, I am running it on Windows 10 through Docker. Is there a way to run the code natively (without Docker)? - You can compile it locally, but you need to have to go SDK installed. But I do not suggest using it in this way since the proxy can die due to exchange errors, so it's must be able to restart.

**Comment by mikekonan** [comment]
There is windows binary in the latest release: https://github.com/mikekonan/freqtrade-proxy/releases/tag/v1.1.0
